const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Behaviors.EightDir,
		C3.Plugins.TextBox,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed
	];
};
self.C3_JsPropNameTable = [
	{ТайловыйФон: 0},
	{ТайловыйФон2: 0},
	{Твёрдый: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{СледитьЗа: 0},
	{Платформер: 0},
	{принцесса: 0},
	{Текст: 0},
	{егорШип: 0},
	{дверь: 0},
	{уровень1: 0},
	{жидкость: 0},
	{дверь3: 0},
	{уровень2: 0},
	{уровень3: 0},
	{уровень4: 0},
	{трололололо: 0},
	{безобидныйегоршип: 0},
	{дверь2: 0},
	{дверь4: 0},
	{управление: 0},
	{Текст2: 0},
	{гг: 0},
	{ТайловыйФон3: 0},
	{забор: 0},
	{"8Направлений": 0},
	{пр2: 0},
	{дверь5: 0},
	{ТайловыйФон4: 0},
	{гастер: 0},
	{клетка: 0},
	{Спрайт4: 0},
	{ТайловыйФон5: 0},
	{"8Направлений2": 0},
	{Платформер2: 0},
	{спнсСзади: 0},
	{Спрайт5: 0},
	{альфис: 0},
	{Спрайт6: 0},
	{ТайловыйФон6: 0},
	{ВводТекста: 0},
	{Текст3: 0}
];

self.InstanceType = {
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	принцесса: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	егорШип: class extends self.ISpriteInstance {},
	дверь: class extends self.ISpriteInstance {},
	уровень1: class extends self.ITextInstance {},
	жидкость: class extends self.ISpriteInstance {},
	дверь3: class extends self.ISpriteInstance {},
	уровень2: class extends self.ITextInstance {},
	уровень3: class extends self.ITextInstance {},
	уровень4: class extends self.ITextInstance {},
	трололололо: class extends self.ISpriteInstance {},
	безобидныйегоршип: class extends self.ISpriteInstance {},
	дверь2: class extends self.ISpriteInstance {},
	дверь4: class extends self.ISpriteInstance {},
	управление: class extends self.ITextInstance {},
	Текст2: class extends self.ITextInstance {},
	гг: class extends self.ISpriteInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	забор: class extends self.ISpriteInstance {},
	пр2: class extends self.ISpriteInstance {},
	дверь5: class extends self.ISpriteInstance {},
	ТайловыйФон4: class extends self.ITiledBackgroundInstance {},
	гастер: class extends self.ISpriteInstance {},
	клетка: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	ТайловыйФон5: class extends self.ITiledBackgroundInstance {},
	спнсСзади: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	альфис: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	ТайловыйФон6: class extends self.ITiledBackgroundInstance {},
	ВводТекста: class extends self.ITextInputInstance {},
	Текст3: class extends self.ITextInstance {}
}